# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2478b4c2b7638f65a35fa007cfe302df3ab3a8f1b06c79313a858e0c33e7ca48b2c2a3f35cfd3aad6f6d9e939894f465b474a7cb320142740ca5237aa80913e

test:
  secret_key_base: 1a436544354bc2a8f1d581ab9bf86459c78295e58a9864cf745627ce67276e194f35299b527324f073b89ebf0f28daa95e6461b9e74302872d962d3bc240b725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
